<?php
declare(strict_types=1);

// Checklyhq SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ChecklyhqUtility::setRegistrar(function (ChecklyhqUtility $u): void {
    $u->clean = [ChecklyhqClean::class, 'call'];
    $u->done = [ChecklyhqDone::class, 'call'];
    $u->make_error = [ChecklyhqMakeError::class, 'call'];
    $u->feature_add = [ChecklyhqFeatureAdd::class, 'call'];
    $u->feature_hook = [ChecklyhqFeatureHook::class, 'call'];
    $u->feature_init = [ChecklyhqFeatureInit::class, 'call'];
    $u->fetcher = [ChecklyhqFetcher::class, 'call'];
    $u->make_fetch_def = [ChecklyhqMakeFetchDef::class, 'call'];
    $u->make_context = [ChecklyhqMakeContext::class, 'call'];
    $u->make_options = [ChecklyhqMakeOptions::class, 'call'];
    $u->make_request = [ChecklyhqMakeRequest::class, 'call'];
    $u->make_response = [ChecklyhqMakeResponse::class, 'call'];
    $u->make_result = [ChecklyhqMakeResult::class, 'call'];
    $u->make_point = [ChecklyhqMakePoint::class, 'call'];
    $u->make_spec = [ChecklyhqMakeSpec::class, 'call'];
    $u->make_url = [ChecklyhqMakeUrl::class, 'call'];
    $u->param = [ChecklyhqParam::class, 'call'];
    $u->prepare_auth = [ChecklyhqPrepareAuth::class, 'call'];
    $u->prepare_body = [ChecklyhqPrepareBody::class, 'call'];
    $u->prepare_headers = [ChecklyhqPrepareHeaders::class, 'call'];
    $u->prepare_method = [ChecklyhqPrepareMethod::class, 'call'];
    $u->prepare_params = [ChecklyhqPrepareParams::class, 'call'];
    $u->prepare_path = [ChecklyhqPreparePath::class, 'call'];
    $u->prepare_query = [ChecklyhqPrepareQuery::class, 'call'];
    $u->graphql_body = [ChecklyhqGraphql::class, 'body'];
    $u->graphql_errors = [ChecklyhqGraphql::class, 'errors'];
    $u->result_basic = [ChecklyhqResultBasic::class, 'call'];
    $u->result_body = [ChecklyhqResultBody::class, 'call'];
    $u->result_headers = [ChecklyhqResultHeaders::class, 'call'];
    $u->transform_request = [ChecklyhqTransformRequest::class, 'call'];
    $u->transform_response = [ChecklyhqTransformResponse::class, 'call'];
});
